//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputsOutputs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=CONSTANTIN-PC;Initial Catalog=InputsOutputs;User Id=inputs-outputs;Passwor" +
            "d=2ZavPeFWE85DJXHA;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;" +
            "ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string DefaultConnection {
            get {
                return ((string)(this["DefaultConnection"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=DESKTOP-3H5HVLF;Initial Catalog=InputsOutputs;User Id=inputs-outputs;Passw" +
            "ord=2ZavPeFWE85DJXHA;Connect Timeout=30;Encrypt=False;TrustServerCertificate=Tru" +
            "e;ApplicationIntent=ReadWrite;MultiSubnetFailover=False")]
        public string DanConnection {
            get {
                return ((string)(this["DanConnection"]));
            }
        }
    }
}
